const gen1 = [
    '1 In the beginning, God created the heavens and the earth. ',
    '2 The earth was formless and empty. Darkness was on the surface of the deep and God’s Spirit was hovering over the surface of the waters.',
    '3 God said, “Let there be light,” and there was light. ',
    '4 God saw the light, and saw that it was good. God divided the light from the darkness. ',
    '5 God called the light “day”, and the darkness he called “night”. There was evening and there was morning, the first day.',
    '6 God said, “Let there be an expanse in the middle of the waters, and let it divide the waters from the waters.” ',
    '7 God made the expanse, and divided the waters which were under the expanse from the waters which were above the expanse; and it was so. ',
    '8 God called the expanse “sky”. There was evening and there was morning, a second day.',
    '9 God said, “Let the waters under the sky be gathered together to one place, and let the dry land appear;” and it was so. ',
    '10 God called the dry land “earth”, and the gathering together of the waters he called “seas”. God saw that it was good. ',
    '11 God said, “Let the earth yield grass, herbs yielding seeds, and fruit trees bearing fruit after their kind, with their seeds in it, on the earth;” and it was so. ',
    '12 The earth yielded grass, herbs yielding seed after their kind, and trees bearing fruit, with their seeds in it, after their kind; and God saw that it was good. ',
    '13 There was evening and there was morning, a third day.',
    '14 God said, “Let there be lights in the expanse of the sky to divide the day from the night; and let them be for signs to mark seasons, days, and years; ',
    '15 and let them be for lights in the expanse of the sky to give light on the earth;” and it was so. ',
    '16 God made the two great lights: the greater light to rule the day, and the lesser light to rule the night. He also made the stars. ',
    '17 God set them in the expanse of the sky to give light to the earth, ',
    '18 and to rule over the day and over the night, and to divide the light from the darkness. God saw that it was good. ',
    '19 There was evening and there was morning, a fourth day.',
    '20 God said, “Let the waters abound with living creatures, and let birds fly above the earth in the open expanse of the sky.” ',
    '21 God created the large sea creatures and every living creature that moves, with which the waters swarmed, after their kind, and every winged bird after its kind. God saw that it was good. ',
    '22 God blessed them, saying, “Be fruitful, and multiply, and fill the waters in the seas, and let birds multiply on the earth.” ',
    '23 There was evening and there was morning, a fifth day.',
    '24 God said, “Let the earth produce living creatures after their kind, livestock, creeping things, and animals of the earth after their kind;” and it was so. ',
    '25 God made the animals of the earth after their kind, and the livestock after their kind, and everything that creeps on the ground after its kind. God saw that it was good.',
    '26 God said, “Let’s make man in our image, after our likeness. Let them have dominion over the fish of the sea, and over the birds of the sky, and over the livestock, and over all the earth, and over every creeping thing that creeps on the earth.” ',
    '27 God created man in his own image. In God’s image he created him; male and female he created them. ',
    '28 God blessed them. God said to them, “Be fruitful, multiply, fill the earth, and subdue it. Have dominion over the fish of the sea, over the birds of the sky, and over every living thing that moves on the earth.” ',
    '29 God said, “Behold, I have given you every herb yielding seed, which is on the surface of all the earth, and every tree, which bears fruit yielding seed. It will be your food. ',
    '30 To every animal of the earth, and to every bird of the sky, and to everything that creeps on the earth, in which there is life, I have given every green herb for food;” and it was so.',
    '31 God saw everything that he had made, and, behold, it was very good. There was evening and there was morning, a sixth day.'
]

const matt1 = [
    '1 The book of the genealogy of Jesus Christ, the son of David, the son of Abraham.',
    '2 Abraham became the father of Isaac. Isaac became the father of Jacob. Jacob became the father of Judah and his brothers. ',
    '3 Judah became the father of Perez and Zerah by Tamar. Perez became the father of Hezron. Hezron became the father of Ram. ',
    '4 Ram became the father of Amminadab. Amminadab became the father of Nahshon. Nahshon became the father of Salmon. ',
    '5 Salmon became the father of Boaz by Rahab. Boaz became the father of Obed by Ruth. Obed became the father of Jesse. ',
    '6 Jesse became the father of King David. David became the father of Solomon by her who had been Uriah’s wife. ',
    '7 Solomon became the father of Rehoboam. Rehoboam became the father of Abijah. Abijah became the father of Asa. ',
    '8 Asa became the father of Jehoshaphat. Jehoshaphat became the father of Joram. Joram became the father of Uzziah. ',
    '9 Uzziah became the father of Jotham. Jotham became the father of Ahaz. Ahaz became the father of Hezekiah. ',
    '10 Hezekiah became the father of Manasseh. Manasseh became the father of Amon. Amon became the father of Josiah. ',
    '11 Josiah became the father of Jechoniah and his brothers at the time of the exile to Babylon.',
    '12 After the exile to Babylon, Jechoniah became the father of Shealtiel. Shealtiel became the father of Zerubbabel. ',
    '13 Zerubbabel became the father of Abiud. Abiud became the father of Eliakim. Eliakim became the father of Azor. ',
    '14 Azor became the father of Zadok. Zadok became the father of Achim. Achim became the father of Eliud. ',
    '15 Eliud became the father of Eleazar. Eleazar became the father of Matthan. Matthan became the father of Jacob. ',
    '16 Jacob became the father of Joseph, the husband of Mary, from whom was born Jesus, who is called Christ.',
    '17 So all the generations from Abraham to David are fourteen generations; from David to the exile to Babylon fourteen generations; and from the carrying away to Babylon to the Christ, fourteen generations.',
    '18 Now the birth of Jesus Christ was like this: After his mother, Mary, was engaged to Joseph, before they came together, she was found pregnant by the Holy Spirit. ',
    '19 Joseph, her husband, being a righteous man, and not willing to make her a public example, intended to put her away secretly. ',
    '20 But when he thought about these things, behold, an angel of the Lord appeared to him in a dream, saying, “Joseph, son of David, don’t be afraid to take to yourself Mary as your wife, for that which is conceived in her is of the Holy Spirit. ',
    '21 She shall give birth to a son. You shall name him Jesus, for it is he who shall save his people from their sins.”',
    '22 Now all this has happened that it might be fulfilled which was spoken by the Lord through the prophet, saying,',
    '23 “Behold, the virgin shall be with child,',
    'and shall give birth to a son.',
    'They shall call his name Immanuel,”',
    'which is, being interpreted, “God with us.”Isaiah 7:14',
    '24 Joseph arose from his sleep, and did as the angel of the Lord commanded him, and took his wife to himself; ',
    '25 and didn’t know her sexually until she had given birth to her firstborn son. He named him Jesus.'
  ]
  

module.exports = {
    gen1,
    matt1
}