name: Main Branch Tests

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    permissions:
      checks: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{matrix.node-version}}
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: |
          npm run test

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Semantic Release
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
